### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by felixSabatie** [PolytechLyon/isi3-test-sabatie-tp7#1]
Hello @Slashgear 
J'ai terminé le code et le rapport pour le TP sur les tests unitaire, je suis prêt pour une code review

**Comment by Slashgear** [comment]
ça me va 😄 

mais petit conseil, quand tu veux faire ça 

https://github.com/PolytechLyon/isi3-test-sabatie-tp7/blob/a052ba4a4ebd6a5899a3f2c31950fab1939e29cf/fizzbuzz/src/main/java/FizzBuzz.java#L40-L43

Au lieu de collect to flux en une list. Tu pourrais très bien faire un `findFirst()' qui te renvoi un Optionel de ton element de flux.

Ensuite tu retourne optionel.orElse(String.valueOf(value))
